name: Backend CI

on:
  workflow_call:
    outputs:
      version:
        description: "New backend version"
        value: ${{ jobs.build.outputs.version }}
      bump_commit_id:
        description: "Auto commit if of bump version"
        value: ${{ jobs.build.outputs.bump_commit_id }}

env:
  WORKING_DIRECTORY: apps/backend

jobs:
  bump-version:
    uses: ./.github/workflows/bump-version.yaml
    with:
      context_name: backend
      working_directory: apps/backend

  build:
    needs: [bump-version]
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update repository
        run: git pull

      - name: Setup Node
        uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version-file: '.node-version'

      - name: Setup Cache Node_Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ steps.setup-node.outputs['node-version'] }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install
    
    outputs:
      version: ${{ needs.bump-version.outputs.version }}
      bump_commit_id: ${{ steps.auto-commit.outputs.commit_id }}
      artifact_name: 'app_${{ needs.bump-version.outputs.version }}'
