name: Bump Version

on:
  workflow_call:
    inputs:
      context_name:
        description: 'Name of the context execution. E.g: frontend or backend'
        required: true
        type: string

      working_directory:
        description: 'Working directory to execute bump'
        default: ''
        required: false
        type: string

    outputs:
      version:
        description: "New frontend version"
        value: ${{ jobs.bump.outputs.version }}
      bump_commit_id:
        description: "Auto commit if of bump version"
        value: ${{ jobs.bump.outputs.bump_commit_id }}

concurrency:
  group: bump-version
  cancel-in-progress: false

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update repository
        run: git pull

      - name: Setup Node
        uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version-file: '.node-version'

      - name: Setup Cache Node_Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ steps.setup-node.outputs['node-version'] }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Setup Cache Scripts
        id: cache-scripts
        uses: actions/cache@v3
        with:
          path: 'scripts'
          key: ${{ runner.os }}-${{ steps.setup-node.outputs['node-version'] }}-node_modules-${{ hashFiles('scripts/**.ts') }}

      - name: Setup Scripts
        if: steps.cache-scripts.outputs.cache-hit != 'true'
        run: yarn build

      - name: Bump version
        id: bump
        run: yarn bump
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: 'action: bump ${{ inputs.context_name }} version to ${{ steps.bump.outputs.version }}'

      - name: Save Auto Commit
        id: auto-commit
        run: echo "commit_id=$(git log --format="%H" -n 1)" >> $GITHUB_OUTPUT
    
    outputs:
      version: ${{ steps.bump.outputs.version }}
      bump_commit_id: ${{ steps.auto-commit.outputs.commit_id }}
