name: Navbar CI/CD

on:
  push:
    branches: 
      - main


permissions: write-all

env:
  FRONTEND_DIRECTORY: apps/sidebar
  BACKEND_DIRECTORY: apps/backend

jobs:
  setup-and-check-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update repository
        run: git pull

      - name: Setup Cache Node_Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ steps.setup-node.outputs['node-version'] }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Setup Cache Scripts
        id: cache-scripts
        uses: actions/cache@v3
        with:
          path: 'scripts'
          key: ${{ runner.os }}-${{ steps.setup-node.outputs['node-version'] }}-node_modules-${{ hashFiles('scripts/**.ts') }}

      - name: Setup Scripts
        if: steps.cache-scripts.outputs.cache-hit != 'true'
        run: yarn build

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - '${{ env.BACKEND_DIRECTORY }}/**'
            frontend:
              - '${{ env.FRONTEND_DIRECTORY }}/**'
    
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
      frontend_changed: ${{ steps.filter.outputs.frontend }}
    
  frontend-ci:
    needs: [setup-and-check-changes]
    uses: ./.github/workflows/frontend.ci.yaml
    secrets: inherit

  backend-ci:
    needs: [setup-and-check-changes, frontend-ci]
    uses: ./.github/workflows/backend.ci.yaml
    secrets: inherit
  

  release:
    needs: [frontend-ci, backend-ci]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Cache Scripts
        id: cache-scripts
        uses: actions/cache@v3
        with:
          path: 'scripts'
          key: ${{ runner.os }}-${{ steps.setup-node.outputs['node-version'] }}-node_modules-${{ hashFiles('scripts/**.ts') }}

      - name: Bump version
        id: bump
        run: yarn bump

      - name: Run auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: 'action: bump repo version to ${{ steps.bump.outputs.version }}'

      - name: Save Auto Commit
        id: auto-commit
        run: echo "commit_id=$(git log --format="%H" -n 1)" >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "app.zip"
          tag: ${{ steps.bump.outputs.version }}
          bodyFile: "README.md"