name: Frontend CI

on:
  workflow_call:
    outputs:
      version:
        description: "New frontend version"
        value: ${{ jobs.package.outputs.version }}
      bump_commit_id:
        description: "Auto commit if of bump version"
        value: ${{ jobs.package.outputs.bump_commit_id }}
      artifact_name:
        description: "App package artifact name"
        value: ${{ jobs.package.outputs.artifact_name }}

env:
  WORKING_DIRECTORY: apps/sidebar

jobs:
  bump-version:
    uses: ./.github/workflows/bump-version.yaml
    with:
      context_name: frontend
      working_directory: apps/sidebar

  package:
    needs: [bump-version]
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update repository
        run: git pull

      - name: Setup Node
        uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version-file: '.node-version'

      - name: Setup Cache Node_Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ steps.setup-node.outputs['node-version'] }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Bump manifest version
        working-directory: apps/sidebar
        run: |
          sed -i s/{{version}}/${{ needs.bump-version.outputs.version }}/g ./manifest.json

      - name: Package app
        run: zip -r "app_${{ needs.bump-version.outputs.version }}.zip" manifest.json
        working-directory: apps/sidebar

      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'app_${{ needs.bump-version.outputs.version }}'
          path: 'apps/sidebar/app_${{ needs.bump-version.outputs.version }}.zip'
    
    outputs:
      version: ${{ needs.bump-version.outputs.version }}
      bump_commit_id: ${{ steps.auto-commit.outputs.commit_id }}
      artifact_name: 'app_${{ needs.bump-version.outputs.version }}'
